from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from app.logger import log_interaction
from app.main import PathwiseState, build_graph


# =============================================================================
# FastAPI App
# =============================================================================

app = FastAPI(title="Pathwise API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Build the graph once at startup — shared across all requests
graph = build_graph()

_FRONTEND_DIST = Path(__file__).resolve().parent.parent / "frontend" / "dist"
_FRONTEND_INDEX = _FRONTEND_DIST / "index.html"

if _FRONTEND_DIST.exists():
    app.mount("/assets", StaticFiles(directory=_FRONTEND_DIST / "assets"), name="assets")


class ChatRequest(BaseModel):
    user_input: str
    lesson_context: str = ""
    attempt: int = 1
    # UUID generated by the frontend at session start; groups all turns in one conversation.
    session_id: str = ""
    # Full chat history sent by the frontend so the LLM and RAG retrieval have
    # context about what was already discussed. Defaults to [] for first turns.
    conversation_history: list[dict] = []


class ChatResponse(BaseModel):
    response_text: str
    intent: str
    attempt: int


@app.get("/health")
def health():
    return {
        "status": "ok",
        "frontend_built": _FRONTEND_INDEX.exists(),
    }


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    """
    Invokes the LangGraph pipeline and returns a guardrail-filtered response.
    The client tracks and sends `attempt` so the escalation persists across turns.
    """
    result = graph.invoke(
        PathwiseState(
            user_input=req.user_input,
            lesson_context=req.lesson_context,
            conversation_history=req.conversation_history,
            retrieved_chunks=[],
            intent="",
            attempt=req.attempt,
            response_text="",
        )
    )

    log_interaction(
        session_id=req.session_id,
        user_input=req.user_input,
        system_output=result["response_text"],
        intent=result["intent"],
        attempt=req.attempt,
    )

    return ChatResponse(
        response_text=result["response_text"],
        intent=result["intent"],
        attempt=req.attempt,
    )


@app.get("/{full_path:path}")
def serve_frontend(full_path: str):
    if _FRONTEND_INDEX.exists():
        requested = _FRONTEND_DIST / full_path
        if full_path and requested.exists() and requested.is_file():
            return FileResponse(requested)
        return FileResponse(_FRONTEND_INDEX)
    return {
        "message": "Frontend build not found. Run `npm run build` in frontend/ before serving the app.",
        "requested_path": full_path,
    }
